### ISSUE TITLE
Clementine features

### ISSUE THREAD

**Issue by agsper** [hansel-reinhart/codex-amiatinus#4]
In reviewing your complete text I observed 3 errors that are all Clementine texts rather than Amiatinus.  It appears that you have begun with a Clementine Vulgate rather than a scanned Amiatinus.

Your transcription may prove more useful if folio numbers (such as 11r or 11v) rather than page numbers are used so that one can easily compare with online photos to verify readings.  Rubrication is also somewhat useful to note, as the red letters often indicate paragraphing or paratextual matter.  XML formatting is standard for academic transcriptions using TEI standards or modifications of TEI such as used by the transcriptions in the Vetus Latina http://itseeweb.bham.ac.uk/iohannes/vetuslatina/manuscripts.html

**Comment by hansel-reinhart** [comment]
> In reviewing your complete text I observed 3 errors that are all Clementine texts rather than Amiatinus. It appears that you have begun with a Clementine Vulgate rather than a scanned Amiatinus.
> 
> Your transcription may prove more useful if folio numbers (such as 11r or 11v) rather than page numbers are used so that one can easily compare with online photos to verify readings. Rubrication is also somewhat useful to note, as the red letters often indicate paragraphing or paratextual matter. XML formatting is standard for academic transcriptions using TEI standards or modifications of TEI such as used by the transcriptions in the Vetus Latina http://itseeweb.bham.ac.uk/iohannes/vetuslatina/manuscripts.html

I appreciate your concerns, but I do find my (although unconventional) method to be adequate for my project. Once more has been transcribed I can quite easily run the entirety through a script to generate a more professional product in xml with the proper folio numbers. I expect there to be many errors and Clementine texts, as the CPDV is being used as a template that I edit through. If you find any transcription errors up to about page 32, then those have been missed by me and I would love them listed for correction.

In fact, I could probably write the xml conversion script with little time and it would be adequate, but I believe it would be best to hold off and wait until I've had the time to divide each individual page first to correctly list the folio pages.

**Comment by hansel-reinhart** [comment]
I have added two new projects to address your concerns:
1. Script for TEI Academic Transcription Standard generation.
2. Addition of Rubrication.

https://github.com/hansel-reinhart/codex-amiatinus/projects
